version: '3'
services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234578
      MYSQL_DATABASE: oander
      MYSQL_USER: test
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"